Repository mathieuPvss/Git-project-ESGI-B3, pull requests merged in 2023-02, with the labels that each got.

#2 PR : Develop
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/issue_form.yml
  .gitignore
  App/src/script.js
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  pull_request_template.md
Labels: documentation

#14 add new html file, close #10
  App/src/index.html
Labels: enhancement

#16 Feature/new menu rose
  App/component/alertButton.js
  App/component/title.js
  App/src/index.html
  App/src/script.js
Labels: enhancement

#18 add menu rose bonbon, close #7
  App/src/index.html
Labels: enhancement

#23 hotfix: major display bug, fixes #22
  App/src/script.js
Labels: bug

#36 Feature/new texte
  App/src/index.html
Labels: enhancement

#40 Feature/add logo
  App/src/index.html
Labels: enhancement
